version: "3.5"

services:
  foxglove:
    image: ghcr.io/jpc/studio:latest
    ports:
      - "8080:8080"

  ros-bridge:
    build: .
    ports:
      - "9090:9090"

  carla:
    image: carlasim/carla:0.9.12
    command: ./CarlaUE4.sh -RenderOffScreen -nosound
    ports:
      - 2000-2002
      #:2000-2002
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
